### PR TITLE
Set federated logout to support SLO

### PR DESCRIPTION
**Pull request by BenCoffeed**
Shortcut Story ID: [sc-28714]

### CODE REVIEW

**Comment by paulfalgout** [comment]
This isn't going to pass the linter.  Also. did it work?

**Comment by BenCoffeed** [comment]
I totally tested this. . .
not sus

**Comment by BenCoffeed** [comment]
I was just trying to help show @nmajor25 what not to do. . .

**Comment by nmajor25** [comment]
With `federated: true` set in my local sandbox, I get completely kicked out of my Google Account (Gmail, Google Calendar, etc.) after signing out in the app.

So this appears to be working.

**Review by paulfalgout — APPROVED** [review]

**Comment by paulfalgout** [comment]
Interesting that there's 2 lines lost of coverage.  I _think_ this isn't explicitly tested now that I look at it, but it is probably covered _some_ times if the tests run slower which is why I didn't catch it :-/

**Pull request merged**
