### PR TITLE
Update Cypress to v13

### PR DESCRIPTION
**Pull request by paulfalgout**
Shortcut Story ID: [sc-41302]

Looks like they fixed it.

### CODE REVIEW

**Comment by paulfalgout** [comment]
ummm. or not..

**Comment by paulfalgout** [comment]
so sometimes it works.. https://cloud.cypress.io/projects/ep9zr6/runs/5609/overview/c31ce9bd-67df-477a-a6a9-efd8ffce6210/replay?roarHideRunsWithDiffGroupsAndTags=1&att=1

**Comment by paulfalgout** [comment]
it seems to be working more often than not

**Review by nmajor25 — APPROVED** [review]
I'm down to upgrade it 👍 . We can always downgrade back to `v12` if things don't go well.

**Pull request merged**
